
create database  Uber
-- Drop Foreign Keys if exist
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DRIVERS_USERISDRI_USERS')
    ALTER TABLE DRIVERS DROP CONSTRAINT FK_DRIVERS_USERISDRI_USERS;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DRIVERVE_BELONGS_T_DRIVERS')
    ALTER TABLE DRIVERVEHICLES DROP CONSTRAINT FK_DRIVERVE_BELONGS_T_DRIVERS;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_DRIVERVE_IS_DRIVEN_VEHICLES')
    ALTER TABLE DRIVERVEHICLES DROP CONSTRAINT FK_DRIVERVE_IS_DRIVEN_VEHICLES;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_PROMOCOD_PROMOCODE_RIDES')
    ALTER TABLE PROMOCODES DROP CONSTRAINT FK_PROMOCOD_PROMOCODE_RIDES;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RIDERATI_RATING_RIDES')
    ALTER TABLE RIDERATINGS__WEAK_ENTITY_ DROP CONSTRAINT FK_RIDERATI_RATING_RIDES;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RIDES_DRIVER_PE_DRIVERS')
    ALTER TABLE RIDES DROP CONSTRAINT FK_RIDES_DRIVER_PE_DRIVERS;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RIDES_USER_REQU_USERS')
    ALTER TABLE RIDES DROP CONSTRAINT FK_RIDES_USER_REQU_USERS;
GO

IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'FK_RIDES_VEHICLE_A_VEHICLES')
    ALTER TABLE RIDES DROP CONSTRAINT FK_RIDES_VEHICLE_A_VEHICLES;
GO

-- Drop Tables
DROP TABLE IF EXISTS DRIVERVEHICLES;
GO
DROP TABLE IF EXISTS PROMOCODES;
GO
DROP TABLE IF EXISTS RIDERATINGS__WEAK_ENTITY_;
GO
DROP TABLE IF EXISTS RIDES;
GO
DROP TABLE IF EXISTS DRIVERS;
GO
DROP TABLE IF EXISTS USERS;
GO
DROP TABLE IF EXISTS VEHICLES;
GO

-- Create USERS Table
CREATE TABLE USERS (
    USERID INT NOT NULL PRIMARY KEY,
    FULLNAME VARCHAR(40),
    EMAIL VARCHAR(30),
    PHONENUMBER VARCHAR(15),
    PASSWORD VARCHAR(255),
    USERTYPE VARCHAR(10),
    REGISTRATIONDATE DATETIME,
    ADDRESS VARCHAR(30)
);
GO

-- Create VEHICLES Table
CREATE TABLE VEHICLES (
    VEHICLEID INT NOT NULL PRIMARY KEY,
    PLATENUMBER VARCHAR(20),
    VEHICLETYPE VARCHAR(20),
    VEHICLEMODEL VARCHAR(10),
    VEHICLECOLOR VARCHAR(10),
    YEAR INT
);
GO

-- Create DRIVERS Table
CREATE TABLE DRIVERS (
    DRIVERID INT NOT NULL PRIMARY KEY,
    USERID INT NOT NULL,
    LICENSENUMBER VARCHAR(10),
    NATIONALID VARCHAR(20),
    DRIVERSTATUS VARCHAR(10)
);
GO

-- Create DRIVERVEHICLES Table
CREATE TABLE DRIVERVEHICLES (
    DRIVERID INT NOT NULL,
    VEHICLEID INT NOT NULL,
    ASSIGNMENTDATE DATETIME,
    CONSTRAINT PK_DRIVERVEHICLES PRIMARY KEY (DRIVERID, VEHICLEID)
);
GO

-- Create PROMOCODES Table
CREATE TABLE PROMOCODES (
    PROMOCODEID INT NOT NULL PRIMARY KEY,
    RIDEID INT,
    CODE VARCHAR(10),
    DISCOUNTPERCENTAGE DECIMAL(5, 2),
    EXPIRYDATE DATETIME,
    MAXUSAGE INT,
    USAGECOUNT INT,
    CONDITIONS VARCHAR(20)
);
GO

-- Create RIDERATINGS Table
CREATE TABLE RIDERATINGS__WEAK_ENTITY_ (
    RIDEID INT NOT NULL PRIMARY KEY,
    RATINGVALUE DECIMAL(3, 2),
    [COMMENT] VARCHAR(45)
);
GO

-- Create RIDES Table
CREATE TABLE RIDES (
    RIDEID INT NOT NULL PRIMARY KEY,
    VEHICLEID INT,
    USERID INT,
    DRIVERID INT,
    RIDEDATETIME DATETIME,
    STARTLOCATION VARCHAR(50),
    ENDLOCATION VARCHAR(50),
    RIDEFEE DECIMAL(10, 2),
    PAYMENTMETHOD VARCHAR(50)
);
GO

-- Add Foreign Keys
ALTER TABLE DRIVERS ADD CONSTRAINT FK_DRIVERS_USERISDRI_USERS
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE DRIVERVEHICLES ADD CONSTRAINT FK_DRIVERVE_BELONGS_T_DRIVERS
    FOREIGN KEY (DRIVERID) REFERENCES DRIVERS(DRIVERID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE DRIVERVEHICLES ADD CONSTRAINT FK_DRIVERVE_IS_DRIVEN_VEHICLES
    FOREIGN KEY (VEHICLEID) REFERENCES VEHICLES(VEHICLEID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE PROMOCODES ADD CONSTRAINT FK_PROMOCOD_PROMOCODE_RIDES
    FOREIGN KEY (RIDEID) REFERENCES RIDES(RIDEID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE RIDERATINGS__WEAK_ENTITY_ ADD CONSTRAINT FK_RIDERATI_RATING_RIDES
    FOREIGN KEY (RIDEID) REFERENCES RIDES(RIDEID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE RIDES ADD CONSTRAINT FK_RIDES_DRIVER_PE_DRIVERS
    FOREIGN KEY (DRIVERID) REFERENCES DRIVERS(DRIVERID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE RIDES ADD CONSTRAINT FK_RIDES_USER_REQU_USERS
    FOREIGN KEY (USERID) REFERENCES USERS(USERID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO

ALTER TABLE RIDES ADD CONSTRAINT FK_RIDES_VEHICLE_A_VEHICLES
    FOREIGN KEY (VEHICLEID) REFERENCES VEHICLES(VEHICLEID) ON UPDATE NO ACTION ON DELETE NO ACTION;
GO
